package config

import "testing"

func Test_test(t *testing.T) {
	t.Error("虽然这是个报错，但你成功运行了！")
}
